openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API for user authentication and authorization
tags:
  - name: Auth
    description: Authentication endpoints for signup and login

paths:
  /api/auth/signup:
    post:
      summary: Create a new user account
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstname
                - lastname
                - username
                - phonenumber
                - email
                - password
              properties:
                firstname:
                  type: string
                  example: John
                lastname:
                  type: string
                  example: Doe
                username:
                  type: string
                  example: johndoe123
                phonenumber:
                  type: string
                  example: "+123456789"
                email:
                  type: string
                  example: john@example.com
                password:
                  type: string
                  format: password
                  example: "StrongP@ssw0rd"
                role:
                  type: string
                  description: Optional user role (e.g., user, admin)
                  example: user
      responses:
        201:
          description: User created successfully
        400:
          description: Username or email not valid
        500:
          description: Server error while signing up

  /api/auth/login:
    post:
      summary: Login to an existing account
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - identifier
                - password
              properties:
                identifier:
                  type: string
                  description: Email, phone number, or username
                  example: john@example.com
                password:
                  type: string
                  format: password
                  example: "StrongP@ssw0rd"
      responses:
        200:
          description: Login successful
        400:
          description: Invalid login credentials
        500:
          description: Server error while logging in

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
